name 'chaznet-hdp'
maintainer 'Chaz Chandler'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures chaznet-hdp'
long_description 'Installs/Configures chaznet-hdp'
version '0.5.1'
depends 'selinux', '~> 0.9'
depends 'chaznet-base', '~> 0.1'
depends 'tarball', '= 0.0.1'
depends 'poise-python', '~> 1.3'
