name 'chaznet-hdp'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures chaznet-hdp'
long_description 'Installs/Configures chaznet-hdp'
version '0.1.3'
depends 'selinux', '~> 0.9.0'
depends 'chaznet-base', '~> 0.1.0'
depends 'tarball', '~> 0.0.1'
